'use client';

import { useState } from 'react';
import AppLayout from '@/components/AppLayout';
import SearchBar from './components/SearchBar';
import SearchResultItem from './components/SearchResultItem';
import { Globe, Image, Newspaper, Video } from 'lucide-react';

// Dummy search results for demonstration
const DUMMY_RESULTS = [
  {
    id: 1,
    title: 'ALION AI Assistant - Official Documentation',
    url: 'https://docs.alion.ai',
    snippet: 'ALION is a powerful AI assistant designed to help you with daily tasks, coding, research, and more. It features voice commands, PDF analysis, and internet search capabilities.',
    category: 'Web',
  },
  {
    id: 2,
    title: 'How to use ALION for Code Generation',
    url: 'https://docs.alion.ai/code-generation',
    snippet: 'Learn how to leverage ALION\'s advanced language models to generate, debug, and optimize code across multiple programming languages including Python, JavaScript, and TypeScript.',
    category: 'Web',
  },
  {
    id: 3,
    title: 'ALION Voice Assistant Setup Guide',
    url: 'https://docs.alion.ai/voice',
    snippet: 'Step-by-step guide to set up and configure the ALION voice assistant for hands-free operation. Supports multiple languages and custom wake words.',
    category: 'Web',
  },
  {
    id: 4,
    title: 'ALION vs ChatGPT - A Comprehensive Comparison',
    url: 'https://blog.alion.ai/comparison',
    snippet: 'Discover how ALION stacks up against other AI assistants. From speed to accuracy to privacy, we break down the key differences in this detailed analysis.',
    category: 'News',
  },
  {
    id: 5,
    title: 'ALION Community Showcase - Image Gallery',
    url: 'https://community.alion.ai/gallery',
    snippet: 'Explore creative works generated by the ALION community. From AI-generated art to complex data visualizations, see what others are building.',
    category: 'Images',
  },
];

export default function SearchPage() {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState(DUMMY_RESULTS);
  const [activeFilter, setActiveFilter] = useState('All');
  const [isSearching, setIsSearching] = useState(false);

  const filters = ['All', 'Web', 'Images', 'News', 'Video'];

  const handleSearch = (searchQuery: string) => {
    if (!searchQuery.trim()) return;
    
    setIsSearching(true);
    // Simulate API call delay
    setTimeout(() => {
      // In real app, this would fetch from a search API
      // For now, we just filter dummy data or keep as is
      setResults(DUMMY_RESULTS);
      setIsSearching(false);
    }, 800);
  };

  const getFilterIcon = (filter: string) => {
    switch(filter) {
      case 'All': return <Globe size={14} />;
      case 'Images': return <Image size={14} />;
      case 'News': return <Newspaper size={14} />;
      case 'Video': return <Video size={14} />;
      default: return <Globe size={14} />;
    }
  };

  return (
    <AppLayout>
      <div className="p-4 sm:p-6 max-w-5xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
            Internet Search
          </h1>
          <p className="text-sm text-gray-400">
            Search the web directly through ALION's intelligent interface
          </p>
        </div>

        {/* Search Bar */}
        <SearchBar 
          query={query}
          setQuery={setQuery}
          onSearch={handleSearch}
          isSearching={isSearching}
        />

        {/* Filters */}
        <div className="flex flex-wrap items-center gap-2 border-b border-white/5 pb-4">
          {filters.map((filter) => (
            <button
              key={filter}
              onClick={() => setActiveFilter(filter)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-all duration-200 ${
                activeFilter === filter
                  ? 'bg-cyan-500/20 text-cyan-400 border border-cyan-400/30'
                  : 'bg-white/5 text-gray-400 border border-transparent hover:bg-white/10 hover:text-white'
              }`}
            >
              {getFilterIcon(filter)}
              {filter}
            </button>
          ))}
        </div>

        {/* Results Count */}
        <div className="flex items-center justify-between">
          <p className="text-xs text-gray-500">
            {isSearching ? 'Searching...' : `Showing ${results.length} results`}
          </p>
        </div>

        {/* Results List */}
        <div className="space-y-4">
          {results.length > 0 ? (
            results.map((result) => (
              <SearchResultItem
                key={result.id}
                title={result.title}
                url={result.url}
                snippet={result.snippet}
                category={result.category}
              />
            ))
          ) : (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <div className="w-16 h-16 rounded-full bg-white/5 flex items-center justify-center mb-4 border border-white/10">
                <Globe size={28} className="text-gray-600" />
              </div>
              <h3 className="text-white font-medium">No results found</h3>
              <p className="text-gray-500 text-sm mt-1">
                Try adjusting your search term or filters
              </p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="pt-4 text-center">
          <p className="text-[10px] text-gray-600 tracking-wider uppercase">
            Results are simulated for demonstration • Powered by ALION v2.5
          </p>
        </div>
      </div>
    </AppLayout>
  );
}